# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Weibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod "AFNetworking"
pod "SDWebImage" 
pod "YYModel" 
pod "FMDB" 
pod "SVProgressHUD" 
pod "pop" 
pod "YYWebImage"
pod "YYImage"
pod "YYCache"
pod "YYWebImage" ,'~> 1.0.4'
 # Pods for Weibo

  target 'WeiboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeiboUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
